services:
  client:
    image: react-client-image
    build: ./projet-test-react
    ports:
      - "4000:4000"
  server:
    image: nest-server-image
    build: ./projet-nest-test
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/nest-test
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
